services:
  frontend:
    container_name: EmegeClient
    build:
      context: ./client
      dockerfile: Dockerfile
    image: emege_client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
  backend:
    container_name: EmegeBackend
    build:
      context: ./server
      dockerfile: Dockerfile
    image: emege_server
    ports:
      - "5000:5007"
    environment:
      - ASPNETCORE_ENVIRONMENT=Local
      - ASPNETCORE_URLS=http://*:5007
      - DOTNET_URLS=http://*:5007
    volumes:
      - ./server:/app